
# Making beautiful charts in Python


This chapter contains the code for some of my most used charts and visualization techniques.

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(reticulate)

use_condaenv("tf")

```

## Importing python packages

Let's load in some libraries that we will use again and again when making charts.

```{python, results='hide', warning=FALSE,message=FALSE}

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import pandas as pd
import numpy as np
import statistics

from scipy.stats import norm
from matplotlib.ticker import EngFormatter, StrMethodFormatter
```

## Importing and cleaning data

Let's start by importing data from a csv and making it usable. In this example, we'll use the weather profile from 2019 in Melbourne, Australia.

We'll also create a new column for a rolling average of the temperature.

```{python, results='hide', warning=FALSE,message=FALSE}

#Note non-ascii character in csv will stuff up the import, so we add this term: encoding='unicode_escape'

# Note: The full file location is this:
# /Users/charlescoverdale/Documents/2021/Python_code_projects/learning_journal_v0-1/MEL_weather_2019.csv

# Import csv
df_weather= pd.read_csv("MEL_weather_2019.csv",encoding='unicode_escape')

# Create a single data column and bind to df
df_weather['Date'] = pd.to_datetime(df_weather[['Year', 'Month', 'Day']])

# Drop the original three field date columns
df_weather = df_weather.drop(columns=['Year', 'Month', 'Day'])

# Let's change the name of the solar exposure column

df_weather = df_weather.rename({'Daily global solar exposure (MJ/m*m)':'Solar_exposure', 
                                'Rainfall amount (millimetres)':'Rainfall',
                                'Maximum temperature (째C)': 'Max_temp'},
                                 axis=1)
                                 
#Add a rolling average
df_weather['Rolling_avg'] = df_weather['Max_temp'].rolling(window=7).mean()

df_weather.head()

```

## Creating a line chart

Now that the data is in a reasonable format (e.g. there is a simple to use 'Date' column), let's go ahead and make a line chart.


```{python, results='hide', warning=FALSE,message=FALSE}

# Now let's plot maximum temperature on a line chart

plt.plot(df_weather['Date'], df_weather['Max_temp'], 
        label='Maximum temperature', 
        color='blue', 
        alpha=0.2, 
        linewidth=1.0,
        marker='')
        
plt.plot(df_weather['Date'], df_weather['Rolling_avg'], 
        label='7-day moving average',
        color='red', 
        linewidth=1.0,
        marker='')

plt.title('Maximum temperature in Melbourne (2019)', fontsize=12)

plt.xlabel('', fontsize=10)
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%b'))
plt.gca().xaxis.set_major_locator(mdates.MonthLocator(interval=1))
#plt.margins(x=0)

plt.ylabel('', fontsize=10)
plt.gca().yaxis.set_major_formatter(StrMethodFormatter(u"{x:.0f}째C"))

plt.gca().spines['top'].set_visible(False)
plt.gca().spines['bottom'].set_visible(True)
plt.gca().spines['right'].set_visible(False)
plt.gca().spines['left'].set_visible(False)

plt.tick_params(
    axis='x',          # changes apply to the x-axis
    which='both',      # both major and minor ticks are affected
    bottom=False,      # ticks along the bottom edge are off
    top=False,         # ticks along the top edge are off
    labelbottom=True)  # labels along the bottom edge are off
    
plt.tick_params(
    axis='y',          # changes apply to the y-axis
    which='both',      # both major and minor ticks are affected
    left=False,      # ticks along the bottom edge are off
    right=False,         # ticks along the top edge are off
    labelleft=True)  # labels along the bottom edge are off    
 
plt.grid(False)
plt.gca().yaxis.grid(True)

plt.legend(fancybox=False, framealpha=1, shadow=False, borderpad=1)

plt.savefig('weather_chart_save.png',dpi=300,bbox_inches='tight')

plt.show()

```





## Bar charts

```{python, results='hide', warning=FALSE,message=FALSE}

# Chart 1: Bar plot

# Get data
country = ['USA', 'Canada', 'Germany', 'UK', 'France']
GDP_per_capita = [45,40,38,16,10]

# Create plot
plt.bar(country, GDP_per_capita, width=0.8, align='center',color='blue', edgecolor = 'black')

# Labels and titles
plt.title('GDP per capita of select OECD countries')
plt.xlabel('Test x label')
plt.ylabel('')

#A dd bar annotations to barchart
# Location for the annotated text
i = 1.0
j = 1.0

# Annotating the bar plot with the values (total death count)
for i in range(len(country)):
    plt.annotate(GDP_per_capita[i], (-0.1 + i, GDP_per_capita[i] + j))
    
# Creating the legend of the bars in the plot
plt.legend(labels = ['GDP_per_capita']) 

# Remove y the axis
plt.yticks([])

# 
plt.savefig('test_bar_plot.png',dpi=300,bbox_inches='tight')

# Show plot
plt.show()

# Saving the plot as a 'png'
#plt.savefig('testbarplot.png')
```

## Stacked bar charts

```{python, results='hide', warning=FALSE,message=FALSE}

labels = ['Group 1', 'Group 2', 'Group 3', 'Group 4', 'Group 5']
men_means = [20, 35, 30, 35, 27]
women_means = [25, 32, 34, 20, 25]
men_std = [2, 3, 4, 1, 2]
women_std = [3, 5, 2, 3, 3]
width = 0.7       # the width of the bars: can also be len(x) sequence

fig, ax = plt.subplots()

ax.bar(labels, men_means, width, yerr=men_std, label='Men')
ax.bar(labels, women_means, width, yerr=women_std, bottom=men_means,
       label='Women')

ax.set_ylabel('Scores')
ax.set_title('Scores by group and gender')
ax.legend()

plt.show()
```

## Line charts

```{python, results='hide', warning=FALSE,message=FALSE}

import matplotlib.ticker as mtick

# Note: you can also get the same result without using a pandas dataframe
#Year = [1920,1930,1940,1950,1960,1970,1980,1990,2000,2010]
#Unemployment_Rate = [9.8,12,8,7.2,6.9,7,6.5,6.2,5.5,6.3]

#Using a pandas dataframe
Data = {'Year': [1920,1930,1940,1950,1960,1970,1980,1990,2000,2010],
        'Unemployment_Rate': [9.8,12,8,7.2,6.9,7,6.5,6.2,5.5,6.3]
       }
  
df = pd.DataFrame(Data,columns=['Year','Unemployment_Rate'])

#Add in a % sign to a new variable
#df['Unemployment_Rate_Percent'] = df['Unemployment_Rate'].astype(str) + '%'
  
plt.plot(df['Year'], df['Unemployment_Rate'], color='blue', marker='o')
plt.title('Unemployment rate (1920-2010)', fontsize=12)
plt.xlabel('Year', fontsize=12)
plt.ylabel('', fontsize=12)
#plt.grid(False)
plt.gca().yaxis.grid(True)
plt.gca().yaxis.set_major_formatter(mtick.PercentFormatter())
plt.show()

```

## Scatter plot

```{python, results='hide', warning=FALSE,message=FALSE}

x =[5, 7, 8, 7, 2, 17, 2, 9,
    4, 11, 12, 9, 6] 
  
y =[99, 86, 87, 88, 100, 86, 
    103, 87, 94, 78, 77, 85, 86]
  
plt.scatter(x, y, c ="blue")

plt.title('Scatterplot title', fontsize=12)
plt.xlabel('x label', fontsize=12)
plt.ylabel('y label', fontsize=12)

plt.show()

```

## Histogram

```{python, results='hide', warning=FALSE,message=FALSE}

np.random.seed(99)

# Using the format np.random.normal(mu, sigma, 1000)
x = np.random.normal(0,1,size=1000)

# Use density=False for counts, and density=True for probability
plt.hist(x, density=False, bins=100)

# Plot mean line
plt.axvline(x.mean(), color='k', linestyle='dashed', linewidth=1)

plt.ylabel('Probability')
plt.xlabel('Mean');

plt.show()
```

## Multiple charts in single plot

```{python, results='hide', warning=FALSE,message=FALSE}

fig, (ax,ax2) = plt.subplots(ncols=2)

ax.plot([0,1],[-35,30])
ax.yaxis.set_major_formatter(EngFormatter(unit=u"째C"))

ax2.plot([0,1],[-35,30])
ax2.yaxis.set_major_formatter(StrMethodFormatter(u"{x:.0f} 째C"))

plt.tight_layout()
plt.show()

```

## Annotating charts

Example taken from the wonderful blog at [Practical Economics](https://practicaleconomics.org/stylised-stylized-economics-charts-in-python-matplotlib-part-1/).

```{python, results='hide', warning=FALSE,message=FALSE}

plt.title('Employment Impact of a Minimum Wage')

# Set limits of chart
plt.xlim(10,70)
plt.ylim(130,200)
   
# Wage supply floor
plt.plot([10,30],[150,150],color='orange')
plt.text(10.5,140.0,"Marginal\nDisutility\nof Labour",size=8,color='black')
   
   
plt.plot([10,40],[160,160],color='lightgrey',linestyle='--')
plt.plot([40,40],[130,160],color='lightgrey',linestyle='--')
   
   
plt.annotate('', xy=(30,138),xytext=(40,138),arrowprops = dict(arrowstyle='<->'))
plt.text(31,140,"Employment\nLoss",size=8, color='k')


plt.axhspan(170,150,xmin=0.0,xmax=20/60,alpha=0.9,color='dodgerblue')
plt.annotate('Additional Surplus to\nEmployed', xy=(20,162),xytext=(30,185),arrowprops = dict(arrowstyle='->'))

# Deadweight loss triangles
trianglex=[30,30,40,30]
triangley=[150,170,160,150]
plt.plot(trianglex,triangley, color='grey')
plt.fill(trianglex,triangley,color='grey')

# Main box
plt.plot([10,30],[170,170],'tab:orange')
plt.plot([30,30],[130,170],'tab:green')
#plt.plot([50,50],[130,170],'tab:red')
plt.text(11,171,"Wage Rate",size=8,color='black')

plt.annotate('Deadweight\nLoss', xy=(32,162),xytext=(38,175),arrowprops = dict(arrowstyle='->'))

#Labour Demand Curve
plt.plot([20,60],[180,140],color='tab:grey')
plt.text(61,135,"Marginal\nProduct\nof Labour\nDemand",size=8,color='black')

#Labour Supply Curve
plt.plot([20,60],[140,180],color='tab:grey')
plt.text(61,180,"Labour\nSupply",size=8,color='k')

plt.show()


```

```{python}

```
